---
- name: validate states on EOS devices
  hosts: eos
  connection: httpapi
  gather_facts: false
  tags: 
    - audit
  
  roles: 
    - validate_device_model_and_SW_release
    - validate_environment
    - validate_interfaces_status
    - validate_lldp_neighbors
    - validate_bgp_neigbhbors
    - validate_routing_table
    - validate_ip_reachability

