---
- name: Make sure the required directory exists
  hosts: localhost
  gather_facts: false
  
  tasks: 

    - name: Make sure the required directory exists
      file:
        path: "{{save_dir}}/conf_generated"
        state: directory
      check_mode: no

- name: configure EOS devices 
  hosts: eos
  connection: httpapi
  gather_facts: false
  
  tasks:

    - name: generate EOS configuration from a template
      template:
        src: "{{playbook_dir}}/templates/config.j2"
        dest: "{{save_dir}}/conf_generated/{{ inventory_hostname }}.cfg"
        trim_blocks: yes
      check_mode: no

    - name: configure EOS devices 
      eos_config:
        src: "{{ playbook_dir }}/outputs/conf_generated/{{ inventory_hostname }}.cfg"
        diff_against: session
        backup: yes
        backup_options:
          dir_path: "{{ playbook_dir }}/backup" 

