---
- name: Make sure the required directory exists
  hosts: localhost
  gather_facts: false
  
  tasks: 

    - name: Make sure the required directory exists
      file:
        path: "{{save_dir}}/backup"
        state: directory
      check_mode: no

- name: backup EOS conf 
  hosts: eos
  connection: httpapi
  gather_facts: false
  
  tasks:

    - name: backup EOS conf 
      eos_config:
        backup: yes
        backup_options:
          dir_path: "{{save_dir}}/backup"

