---
    - name: collect power supplies status
      eos_command:
        commands: "show environment power | json"
      register: power

    - name: validate power supplies status 
      assert:
        that:
          - item.value.state == 'ok'
        quiet: true
      loop: "{{ power.stdout_lines.0.powerSupplies|dict2items }}"    
      ignore_errors: "{{ validation.mode.loose }}"

    - name: collect fan status
      eos_command:
        commands: "show environment cooling | json"
      register: fan

    - name: validate fan status (power supplies)
      assert:
        that:
          - item.status == 'ok'
        quiet: true
      loop: "{{ fan.stdout_lines.0.powerSupplySlots }}"    
      ignore_errors: "{{ validation.mode.loose }}"

    - name: validate fan status (fan tray) 
      assert:
        that:
          - item.status == 'ok'
        quiet: true
      loop: "{{ fan.stdout_lines.0.fanTraySlots }}"    
      ignore_errors: "{{ validation.mode.loose }}"

    - name: validate temperature 
      eos_command:
        commands: "show environment temperature | json"
        wait_for: result[0].systemStatus eq 'temperatureOk'
      ignore_errors: "{{ validation.mode.loose }}"
